### ISSUE TITLE
Inverted point on 2-point pass/fail grading scale

### ISSUE THREAD

**Issue by Sacus1** [KY246/jpdBlock#7]
### Description
When using the **2-point pass/fail grading scale** with the following settings:
- Points earned for getting a card wrong: **-1**
- Points earned for getting a card right: **2**

The system behaves incorrectly:
- I earn **2 points** when I fail a card.
- I lose **1 point** when I pass a card.

### Expected Behavior
- When a card is marked wrong, **-1 point** should be earned.
- When a card is marked right, **2 points** should be earned.

### Actual Behavior
- **+2 points** are awarded when a card is marked wrong.
- **-1 point** is deducted when a card is marked right.

### Steps to Reproduce
1. Set up the 2-way grading system with:
   - Points for wrong: **-1**
   - Points for right: **2**
2. Attempt a card and fail it.
3. Attempt a card and pass it.
4. Observe the points awarded/deducted.

### Environment
- **Version:** 2.1
- **OS:** Windows
- **Browser:** Firefox

I'm sorry to bother you with another issue

**Comment by KY246** [comment]
This should be fixed in 2.1.1.
